### ISSUE TITLE
CustomArmor + Optifine = no working all configs all variants

### ISSUE THREAD

**Issue by MrJorman** [LoneDev6/ItemsAdder#2436]
### What happened?

i use default configs Optifine ItemsAdder, and my armor no working. Leather armor also no working.

![image](https://user-images.githubusercontent.com/55187962/226617273-a8f80d55-1c10-4626-b6a3-4420f3642d39.png)

### Steps to reproduce the issue

1. add custom armor
2. /iazip
3. Optifine + itemsaader = broken

### Server version

Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Paper-442 (MC: 1.19.3)
* You are running the latest version

### Problematic items yml configuration file (optional)

```shell
nbt.itemsadder.namespace=caverns_chasms
nbt.itemsadder.id=necromium_chestplate
type=armor
items=leather_chestplate
texture.leather_layer_1_overlay=fffffe_1.png
texture.leather_layer_2_overlay=fffffe_2.png
texture.leather_layer_1=fffffe_1.png
texture.leather_layer_2=fffffe_2.png
weight=9999
```

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/226619603-6dece1f2-03c6-484a-a304-c4f625d1918f.png)

**Comment by MrJorman** [comment]
minecraft -> optifine -> cit 
all files here.

**Comment by MrJorman** [comment]
I'm already sitting for the 3rd hour, I can't do it, although everything worked before, it seems to me that you broke something again and I'm just sitting there.

**Comment by LoneDev6** [comment]
I said it 3 times: DO NOT USE GITHUB AS A REALTIME CHAT! I ALREADY SAID I RECEIVE 1 NOTIFICATION FOR EACH MESSAGE!
If you need to add more information add it by editing your previous message!
Stop sending multiple messages to gain attention.
You're one of the reasons why updates take long to be delivered. I wasted 1 hour today on your reports while I could have worked on the plugin update.

> although everything worked before

Contextualize what you mean by "before", I'm not a magician, I cannot guess what you mean by "before", before what?

I didn't change anything about armors in recent updates so I have no clue what are you referring to.
ItemsAdder already generates them automatically for your custom armors.
Each feature is ALWAYS tested extensively to make sure to deliver a working update.

Every time you report an issue:
- vague report with little information
- you always don't follow the guidelines and totally ignore what I write
- you always try to gain more attention over others reports, this is an insult to other customers
- always act in an arrogant way like I'm your slave and supposed to answer your questions daily

You were banned 2 times from my Discord before.
Remember the various reasons and remember that you begged me for a week to get unbanned and promised you wouldn't act that way again. You spent 2 years insulting my staff, my work and violating the community guidelines multiple times.
Guess what? You started acting like that again.
(Just a little context for anyone who will read this page https://imgur.com/a/8Z1lLdc )

Now stop ALWAYS blaming my work. I don't know why you keep spending time criticizing the plugin even though there are alternatives to ItemsAdder you can use. Maybe because you like the plugin? Then stop acting like that.

This is an Optifine 1.19.3 bug. This has NOTHING to do with ItemsAdder.

# I wasted time to do what you could have done:

## Optifine 1.18.2

![image](https://user-images.githubusercontent.com/27242001/226641025-8999a044-dd4b-41aa-8526-569cc9712567.png)

![image](https://user-images.githubusercontent.com/27242001/226641152-d9ee706a-4de8-4f5c-b9c1-230d54c51068.png)


## Optifine 1.19.2

![image](https://user-images.githubusercontent.com/27242001/226637619-6c6a4217-ade0-4f20-be64-0462656b6da8.png)

![image](https://user-images.githubusercontent.com/27242001/226637783-d8988324-1e10-49ad-92fa-e7199bd0287e.png)


## Optifine 1.19.3 <---- OPTIFINE BUG!

![image](https://user-images.githubusercontent.com/27242001/226638220-84d6ed58-9936-4a58-b5b1-96da4b9b1308.png)

![image](https://user-images.githubusercontent.com/27242001/226638386-6966e2a3-ca4a-4c31-bc82-fb46dd4be85c.png)

**Comment by MrJorman** [comment]
I love you and your plugin
