### ISSUE TITLE
[BUG] override is not created with a set model id & generate: false

### ISSUE THREAD

**Issue by PhanaticD** [LoneDev6/ItemsAdder#284]
```
info:
  namespace: slimefun
items:
  multimeter:
    resource:
      material: CLOCK
      generate: false
      model_id: 4000
```

the model_id in the override file is set to 1, not 4000, also the folder is set to auto_generated instead of items

```
{
  "parent": "item/generated",
  "textures": {
    "layer0": "item/clock"
  },
  "overrides": [
    {
      "predicate": {
        "custom_model_data": 1
      },
      "model": "slimefun:auto_generated/multimeter"
    }
  ]
}
```

**Comment by PhanaticD** [comment]
actually it seems like the file is not created at all when generate is set to false and it was just left over from when I had it set to true

I am guessing the bug is that the overrides are not being created when generate is set to false, even though they still should be as thats the whole point of having it combined with the custom model id

**Comment by LoneDev6** [comment]
Hello!
You can fix like this:
```Yaml
    resource:
      material: CLOCK
      model_id: 4000
      generate: false
      model_path: "item/multimeter"
```

remember also to set the namespace to "slimefun" in the top part of the yml and also name the folder like this

**Comment by tinkeringmatt** [comment]
Okay so just so I understand
In the config file you used model_id: to set an id number of sorts.
Now this id refers to the model generated from this process, including the texture.
However can you call lets say 4000 using an item in another config file by using something like this

Like I've used this for adding extra stuff manually to the items, so that some are unique from the others

/give player stick 1 
{
   display:{Name:"[{\"text\":\"Random Teleport\"}]",},
   CustomModelData:41,
   itemsadder:
   {
      id:"golden_coupon",
      namespace:itemsadder
   }
}

But instead after setting that custom model_id in the config file, I could call specifically for it for any item using CustomModelData:4000
Does that work or make sense?

**Comment by PhanaticD** [comment]
I have no idea what you are talking about tinkeringmatt

as per our discussion on discord, the custom_model_data is set to the wrong number for the first instance of a added item, so in this case this was the first custom clock so it go the wrong ID

for the other part of my issue I was just missing model_path

**Comment by tinkeringmatt** [comment]
Sorry phanaticD
I was linked to this conversation by lonedev6 after I send a question.

I apologize if my question interfered with you in some way

**Comment by LoneDev6** [comment]
I'm closing this issue since it should be fixed in the new update i will release.
comment on this if after update you still find strange behaviour.

anyway i added a new part in the tutorials about model_id: https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/resource#manually-specify-custom_model_data
