### ISSUE TITLE
[BUG] Edit vanilla .json file without having IA to overwrite it

### ISSUE THREAD

**Issue by ICEconchy** [LoneDev6/ItemsAdder#310]
**Describe the bug**
So when editing iron_ingot.json in the hosted resource pack. It seems to revert to previous state when using /iazip

**To Reproduce**
Edit a resource pack file in the minecraft directory

**Expected behavior**
Keep state

**Info (please complete the following information):**
 - Server version: paper 1.15.2-R0.1-SNAPSHOT (git-Paper-372)
 - Client version: Vanilla
 - Plugin version: 2.0.28

**Additional context**
Tried using my hosts inbuilt file editor and ftp

**Comment by LoneDev6** [comment]
Similar issue:
https://github.com/LoneDev6/Issues-ItemsAdder/issues/154
https://github.com/LoneDev6/Issues-ItemsAdder/issues/56
https://github.com/LoneDev6/Issues-ItemsAdder/issues/150

I'd have to allow modifications of these files.
Exactly what are you trying to add/change in this file?

**Comment by ICEconchy** [comment]
Editing vanilla json files allows for compatibility between plugins that use resource packs. These include, space, quality armory and another's that do not allow for editing.

**Comment by LoneDev6** [comment]
Do you need to add CustomModelData or durability values?

**Comment by ICEconchy** [comment]
I'd allow both. Currently I'm using custom model data.

**Comment by LoneDev6** [comment]
It's an easy fix then, if you just need to use custommodeldata.

Create a new namespace named "custommodeldata" or "fixes" or idk, you can decide.

Inside create a file and create these fake items.
For example if you want to set custommodeldata to 49 because a plugin is using it to show a particular item you can create this item: https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/resource#manually-specify-custom_model_data

```
info:
  namespace: slimefun
items:
  carbonado:
    resource:
      material: PLAYER_HEAD
      generate: true
      model_id: 49
      textures:
      - slimefun/carbonado.png
```

**Comment by LoneDev6** [comment]
Check also this: 
https://github.com/LoneDev6/Issues-ItemsAdder/issues/284

**Comment by LoneDev6** [comment]
Related to: https://github.com/LoneDev6/ItemsAdder/issues/283
