### ISSUE TITLE
[BUG] Hit through inventory 

### ISSUE THREAD

**Issue by a7ssan** [LoneDev6/ItemsAdder#331]
**Describe the bug**
when you open /ia menu and click to any item your hand will move

**To Reproduce**
1. Open /ia
2. Click any item
3. magic happen
4. no errors in console

**Expected behavior**
Hit through inventory

**Video**
https://www.youtube.com/watch?v=S2I0Ll5FpkI

**Info (please complete the following information):**
 - Server version: Spigot 1.16.1 (latest build)
 - Client version: fabric 1.16.1 & vanilla 1.16.1
 - Plugin version: 2.0.37

**Comment by 100petr** [comment]
Same in paperspigot 1.16.1

**Comment by 100petr** [comment]
I'd say it's a spigot or vanilla bug. I do it even with a slimefun book.

**Comment by Xuwznln** [comment]
If you use item to open itemsadder's menu, your hand will left click and it will also call playerInteractEvent.
When I use the attach-command function from a plugin called CMI, whenever I click a item in the menu, it will call playerInteractEvent causing issuing /ia and open the main menu, instead of opening the submenu.
Other menu plugins like deluxemenu wont cause that, the hand wont click.

**Comment by LoneDev6** [comment]
Why did you bind /ia to playerInteractEvent? Everytime a player interacts with anything will open the ItemsAdder GUI?

**Comment by Xuwznln** [comment]
No, but everytime I click an item in the ia gui, it will call playerInteractEvent

**Comment by LoneDev6** [comment]
I will try to fix this, thanks

**Comment by LoneDev6** [comment]
Seems a Spigot/Vanilla bug: https://hub.spigotmc.org/jira/browse/SPIGOT-5974
