### ISSUE TITLE
[Bug] Loadbefore warning from ItemsAdder

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/ItemsAdder#382]
**Describe the bug**
ItemsAdder will post the following loadbefore warning when another plugin uses the same (not-relocated) dependency.

```
[11:51:54 WARN]: [ItemsAdder] Loaded class org.apache.commons.io.filefilter.IOFileFilter from InteractiveBoard v7.7 which is not a depend, softdepend or loadbefore of this plugin.
```

**To Reproduce**
1. Just run ItemsAdder alongside a plugin that uses the same dependency

**Expected behavior**
ItemsAdder should have the dependency relocated to prevent such warnings.

**Screenshots**

**Info (please complete the following information):**
 - Server version: PaperMC 1.16.2
 - Client version: Minecraft (Fabric Loader) 1.16.2
 - Plugin version: 2.0.46

**Additional context**
This is only a minor error and doesn't cause much problems, but should still be fixed.

**Comment by LoneDev6** [comment]
Hello!
Seems InteractiveBoard has "org.apache.commons.io" lib inside itself, probably this plugin loads before LoneLibs so it overwrites my version of "org.apache.commons.io" which is included in LoneLibs.
There should be no issue, it's just a Spigot warning that tells you that this plugin has overwrited a lib in memory because it has the same java package.

You can safely ignore it as long as it's the same "org.apache.commons.io" version.
I have no way to fix this problem, I'd have to find a way to force LoneLibs to be loaded as first plugin, but I didn't find anything to do that

**Comment by Andre601** [comment]
The easiest solution is to just relocate the lib inside LoneLob, so that InteractiveBoard doesn't share this path.

And even if LoneLib would load before IB, would the issue persist, but this time vice-verca.

**Comment by LoneDev6** [comment]
Yep you're right.
Anyway, I'd prefer to keep the package with its original name
