### ISSUE TITLE
[BUG] Orientable block not working

### ISSUE THREAD

**Issue by GreenTree0** [LoneDev6/ItemsAdder#462]
**Describe the bug**
I'm trying to reproduce a pumpkin but in another color, I need it to adapt its faces to the player position when placing (and Minecraft can do this: block/orientable), but it seems like ItemsAdder is changing the orientation and the face of my pumpkin is every time at the left (with the front texture).

**To Reproduce**
Setup any 1.16.3 or less IA server.
Try to add a block with a custom .json as a block/orientable with different textures for front/side/top.
Then you will see that your block orientation is not working and will always be the same. 

**Expected behavior**
Well, I want the pumpkin to face the player when he places it.

**Screenshots**
https://www.noelshack.com/2020-44-6-1604106361-bug-ia.png

**Info (please complete the following information):**
 - Server version: Spigot 1.16.3
 - Client version: Normal 1.16.3
 - Plugin version: 2.1.10

**Comment by LoneDev6** [comment]
Hello,
the only way to achieve this is to create a model using Blockbench and making a new item with furniture behaviour instead of block type. There are a lot of furnitures examples in my plugin, you can check all the examples.
Custom blocks cannot be orientable sadly, it's a Minecraft limitation I cannot bypass
