### ISSUE TITLE
Mount on vehicle cause disconnet

### ISSUE THREAD

**Issue by WindUnwaken** [LoneDev6/ItemsAdder#49]
https://pastebin.com/N8fPVMwG

Waterfall-294
Paper-195
ItemsAdder-1.1.25
Centos Java11

**Comment by WindUnwaken** [comment]
empty packet error, waterfall have option to allow, currently resolve this, but it should be valid packet

**Comment by LoneDev6** [comment]
Can you provide a tutorial or property name to be changed in order to fix this bug on Waterfall?

Thanks

**Comment by WindUnwaken** [comment]
Duplicate of # 50

waterfall.yml 
allow_empty_packets: true

or update to Waterfall-295

**Comment by LoneDev6** [comment]
Thanks! I hope this will help someone

**Comment by Padlick01** [comment]
Can confirm this thing. 
You have to use Waterfall if you have a network and want to use vehicles, a bit annoying (because of empty packets, bungee doesnt like that, Waterfall has an option).

But as I used Bungeecord, I got this error sometimes:
https://pastebin.com/mf3xZ9Yj

(Lone told me to write it here)

**Comment by BillyGalbreath** [comment]
Is this still a problem on the latest Waterfall build?

Waterfall [removed the ignore empty packets option](https://github.com/PaperMC/Waterfall/commit/2b3b0ec9982a4526aa1edc305254e1a08bfc3743), and instead made it a default behavior (it always ignores empty packets now).

**Comment by LoneDev6** [comment]
Thanks @BillyGalbreath for the clarification
