### ISSUE TITLE
[BUG]  Sudden Lag on Paper 1.16.4

### ISSUE THREAD

**Issue by GriffinChen** [LoneDev6/ItemsAdder#497]
![image](https://user-images.githubusercontent.com/48965379/98983241-7e9d8180-24ee-11eb-8df3-41987f4a5095.png)
Somehow the Server will lag at a specific point when the player breaks a block, and this error message appeared in the console

**Comment by LoneDev6** [comment]
@SlyJacobTheBeast @GriffinChen 
Seems the problem is elsewhere.
There seem to be a problem on loading loots for a specific block, this lead to problems on block breaking.

I suggest you to enable loots loading logs in config.yml to identify if something fails to load.
`log-loots-loading: true`
If not, please send me your complete log.
