### ISSUE TITLE
[BUG] Leather armor textures override

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [LoneDev6/ItemsAdder#503]
**Describe the bug**
Something in the plugin creates a leather armor textures that override any texture pack you are using. I haven't found any item that's causing that. Removing the textures doesn't work as the plugin generates them again. Located in ItemsAdder\data\resource_pack\assets\minecraft\textures\item

**Info (please complete the following information):**
Server version: PaperMC 1.16.4
Client version: Forge 35.0.2
Plugin version: 2.1.18

**Comment by LoneDev6** [comment]
This plugin retextures leather armors in order to "clean them up" from the details, then applies a specific color to them in order to fake minerals colors. For example green for the emerald, red for the ruby, etc.

I cannot disable that or the custom armors will look different.
Do you have any solution?
