### ISSUE TITLE
I want to know how to add HUDs. Do you have any information on how to do this?

### ISSUE THREAD

**Issue by nopppadad22** [LoneDev6/ItemsAdder#575]
I want to know how to add HUDs. Do you have any information on how to do this?

**Comment by LoneDev6** [comment]
Hello, huds are the most difficult thing to add to itemsadder, currently there is no tutorial as I have to make a very detailed guide and currently I have no time due to the high amount of support requests.

What you can do is take a look at the multiple addons that implemented HUDs feature to see how they added it, and try to add your own.
If you need to add a more detailed feature you have to implement the Java API, but if you want to add a simple hud similar to the thirst one you can do it without any coding knowledge (take a look at the realcraft namespace in default itemsadder files).

Here are all the itemsadder addons:
https://addons.plugin.ga/itemsadder/

here are the addons implementing the huds:
https://www.spigotmc.org/resources/betterhud-custom-minecraft-hud-itemsadder-addon.84180/
https://www.spigotmc.org/resources/plugin-servermonitor-itemsadder-addon.78112/

anyway as I said, the easiest way to implement huds is to take a look at my default thirst hud included in the realcraft namespace
