### ISSUE TITLE
[BUG] Drops

### ISSUE THREAD

**Issue by MrFreasy** [LoneDev6/ItemsAdder#576]
I would like to add a feature in my server that interface with itemsadder.

I’d like it to be announced on the server when you find a certain item by killing a mob or breaking a block.
The problem is that itemsadder does not modify the list of drops in various events, such as Entitydeathevent and Blockbreakevent.

How can I solve the problem?

**Comment by LoneDev6** [comment]
You can listen to the [itemspawn event](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/ItemSpawnEvent.html) and check if there is any player around, the nearest player should be the one who killed mob / mined block and got the item.
Also check if the player has recently break a block or killed a mob (implement that via metadata or hashmap, listen to blockbreak and kill events).

For now there is no other way as the API doesn't provide that information, I may add it in the future.
You can open a feature request instead of a bug request
