### ISSUE TITLE
Furnace duplication exploit using recipe book

### ISSUE THREAD

**Issue by BillyGalbreath** [LoneDev6/ItemsAdder#6]
Custom items that have a furnace recipe can be duplicated in the furnace using the recipe book and some normal clay balls.

While the custom item is smelting, spam click the recipe book clay brick recipe to transfer the clay balls into the custom item.

This doesnt seem to always happen, maybe depends on where the items sit in the inventory (not sure). Sometimes clicking the recipe book does nothing and other times it works every time (seen in video).

Video example: https://youtu.be/CWzPHIexwnc

**Comment by LoneDev6** [comment]
could be a spigot bug.. as it's strange that the recipe book doesn't check for NBT data to match before doing anything, what do you think?

**Comment by LoneDev6** [comment]
I'll be able to fix this if Spigot staff approves this request: https://hub.spigotmc.org/jira/browse/SPIGOT-5026

**Comment by LoneDev6** [comment]
Or when Paper spigot merges this: https://github.com/PaperMC/Paper/pull/2107

**Comment by LoneDev6** [comment]
@BillyGalbreath do you have any advice? I can't manage to fix this as Minecraft doesn't check for NBT data before incrementing item

**Comment by LoneDev6** [comment]
Latest spigot update should have fixed the issue completely: 7ef2b20d SPIGOT-3308: RecipeIterator cannot longer remove recipes

Let me know

**Comment by LoneDev6** [comment]
We have to wait spigot to fix this issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5320

**Comment by LoneDev6** [comment]
Fixed with a workaround

**Comment by LoneDev6** [comment]
I have to find a way to fix this problem without using Paper api, I'll try disabling custom recipes viewing from recipebook as it's the cause of dupe

**Comment by LoneDev6** [comment]
Fixed intercepting recipebook recipes registration via protocollib and cancelling them only for custom itemsadder recipes

**Comment by ofunny** [comment]
As far as see could you fix this problem on Paper servers (might even no longer exist in general).
Since the majority of server owners runs PaperMC and not Spigot these days, would you consider allowing custom recipes within the "Knowledge Book" for PaperMC servers again.

I really think that this is an important feature, because it would give players a vanilla way of discovering knew recipes without having to learn new commands or using GUIs somebody need to explain them first that they exist.

So, yeah, would be really nice to re-allow custom recipes within the "Knowledge Book" on PaperMC servers.

**Comment by LoneDev6** [comment]
@ofunny they are already on recipes book and this issue is from 2019.
